version: "3.7"

services:
  nginx:
    build:
      context: ./docker/development/nginx
      dockerfile: nginx.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "80:80"
  php-fpm:
    build:
      context: ./docker/development/php-fpm
      dockerfile: php-fpm.Dockerfile
    volumes:
      - ./:/app
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bb
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bb
    volumes:
      - ./docker/pgsql/data:/var/lib/postgresql/data

#  mysql:
#    image: mysql:8
#    ports:
#      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password --sql_mode=''
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: bb
#      MYSQL_USER: bb
#      MYSQL_PASSWORD: secret
#      MYSQL_ROOT_PASSWORD: secret
